export default {
  SET_ALL_PRODUCT_LIST: "SET_ALL_PRODUCT_LIST",
  SET_PRODUCT_LIST_TO_SHOW: "SET_PRODUCT_LIST_TO_SHOW",
  SET_LIMIT_PER_PAGE: "SET_LIMIT_PER_PAGE",
  SET_PAGE_NUMBER: "SET_PAGE_NUMBER",
};
